name: Docker Image CI

env:
  AZURE_WEBAPP_NAME: petapi

# Triggers - what will cause this workflow/pipeline to run
on:
  push:
    branches:
      - main
        dev
        feat* #feat-{some-name}
    paths:
      - Week3/PetTracker/**
  pull_request:
    branches: 
      - main
        dev
        feat*
    paths:
      - Week3/PetTracker/**
  workflow_dispatch: # a manual trigger, so I get a button to press to start the pipeline if I want to!

jobs: # the job is the set of tasks that will be hosted and run on the same agent
  build: #the name of the job
    runs-on: ubuntu-latest #specifies the type/OS of the build agent 
    # githubs agents are a blank slate with every workflow
    # private build agent can speed up the workflow by already having dependencies installd

    steps: # what processess/steps will the JOB need to do?
    # Step 1: clone the repo
    - name: Checkout
      uses: actions/checkout@v4

    # Step 2: install docker to run out build
    - name: Docker Setup Buildx
    # You may pin to the exact commit or the version.
    # uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5
      uses: docker/setup-buildx-action@v3.8.0

    # Step 3: login to docker
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.RH_DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.RH_DOCKER_PASS }}

    # Step 4: build and push a docker image
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.11.0
      with:
        context: ./Week3/PetTracker/
        file: ./Week3/PetTracker/Dockerfile
        push: true
        tags: index.docker.io/hawkinsr/pettracker:latest, index.docker.io/hawkinsr/pettracker:${{ github.sha }}

    # Step 5: deploy the image to Azure
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: index.docker.io/hawkinsr/pettracker:${{ github.sha }}
